

from .temple_categeory_views import *
from .temple_priority_views import *
from .goshala_category_views import *
from .event_categeory_views import*
from .goshala_views import GetIndianGoshalas, GhoshalaPost,GoshalaView,GetbyStateLocationGoshalas,GetbyDistrictLocationGoshalas,GetbyBlockLocationGoshalas,GetGlobalGoshalas,GetIndianGoshalas,GetGoshalasByLocation,InactiveGoshalaAPIView,GetInactiveGoshalaByFieldView,GetInactiveGoshalasByLocation
from .event_views import *
from .country_views import *
from .state_views import StateViews
from .district_view import DistrictVIew
from .block_views import BlockView
from .village_views import VillageView,GetVillages,search_village,InactiveVillageAPIView,GetInactiveVillageByFieldView,GetVillagesByLocation,ShareContentView,ShareTemplePageView
from .main_view import TempleMain,GoshalaMain, EventsMain
from .temple_views import InactiveTempleAPIView,TempleView,TempleDetailView, GetItemByfield_InputView,Templepost,GetIndianTemples,GetGlobalTemples,GetItemByfield_location,GetbyDistrictLocationTemples,GetbyBlockLocationTemples,GetbyCountryLocationTemples,filters_by_iteams,GetTemplesByLocation,GetInactiveTempleByFieldView,GetInactiveTemplesByLocation,GetCityTemplesByLocation,GetTownTemplesByLocation,GetStateTemplesByLocation
from .comment_views import CommentView
from .register_views import Registerview,LoginView,GetProfile,GetProfileById,ProfileUpdate,updateprofile,DeleteImage,updateRoots,DeleteProfileView,DeletePujariView,DeleteMemberView,AdminProfileById,UsersStatusView
from .connect_views import ConnectView
from .member_views import MemberView
from .home_views import HomeView
from .chatviews import ChatViews
from .add_temple_details_view import AddTempleDetailsView,AddmoretempledetailtemplemergeAPIView
from .media_view import MediaView
from .add_event_details_view import AddEventDetailsView,AddMoreEventDetailEventMergeAPIView
from .add_goshala_details_view import AddGoshalaDetailsView,AddMoreGoshalaDetailGoshalaMergeAPIView
from .add_village_details_view import AddVillageDetailsView,AddmorevillagedetailvillagemergeAPIView
from .temple_main_category_views import TempleMainCategoryViewSet
from .temple_nearby_hotels_view import TempleNearbyHotelView,GetHotelsByLocation,InactiveHotelAPIView,GetInactiveHotelsByLocation
from .tourismplace_view import TempleNearbyTourismPlacesView,GetTourismByLocation,InactiveTourismPlaceAPIView,GetInactiveTourismByLocation
from .transport_view import TempleTransportViewSet
from .tour_operator_view import TourOperatorViewSet,TourOperatorsByLocation,InactiveTourOperatorAPIView,InactiveTourOperatorsByLocation
from .tour_guide_view import TourGuideViewSet,TourGuidesByLocation,InactiveTourGuideAPIView
from .temple_festival_view import TempleFestivalViewSet
from .nearby_hospitals_view import NearbyHospitalViewSet,GetHospitalsByLocation,InactiveNearbyHospitalAPIView,GetInactiveHospitalsByLocation
from.socialactivity_view import SocialActivityViewSet
from .prayers_and_benefits_view import PrayersAndBenefitsViewSet
from .temple_facilities_view import TempleFacilitiesViewSet
from .pooja_timing_view import TemplePoojaTimingViewSet
from .favorite_temples_views import FavoriteTempleViewSet
from .resturents_view import TempleNearbyRestaurantView,GetRestaurantsByLocation,InactiveRestaurantAPIView,GetInactiveRestaurantsByLocation
from .pujari_category_view import PujariCategeoryview
from .pujari_subcategory_view import PujariSubCategoryViewSet
from .visit_temple_view import VisitTempleViewSet
from .ambulance_facility_view import AmbulanceFacilityView
from .blood_bank_view import BloodBankView,GetBloodBanksByLocation,InactiveBloodBankAPIView,GetInactiveBloodBanksByLocation
from .fire_station_view import FireStationView
from .police_station_view import PoliceStationView
from .pooja_stores_view import PoojaStoreView,GetPoojaStoresByLocation,InactivePoojaStoreAPIView,GetInactivePoojaStoresByLocation
from .nearby_vetarnary_hospital_view import NearbyVeterinaryHospitalViewSet,GetVeterinaryHospitalsByLocation,InactiveVeterinaryHospitalAPIView,GetInactiveVeterinaryHospitalsByLocation
from .accommodation_view import AccommodationView
from .village_famous_personalities_view import VillageFamousPersonalityViewSet
from .village_artists_view import VillageArtistViewSet
from .village_devlopment_facilities_view import VillageDevelopmentFacilityViewSet
from .village_cultural_profile_view import VillageCulturalProfileViewSet
from .village_geographic_view import VillageGeographicViewSet
from .school_view import VillageSchoolViewSet
from .bank_view import VillageBankViewSet
from .college_view import VillageCollegeViewSet
from .market_view import VillageMarketViewSet
from .postoffice_view import VillagePostOfficeViewSet
from .sportsground_view import VillageSportsgroundViewSet
from .welfare_home_category_view import WelfareHomesCategoryViewSet
from .welfare_homes_view import WelfareHomesViews,GetWelfareHomesByLocation,InactiveWelfareHomesAPIView,GetInactiveWelfareHomesByLocation
from .sso_login_view import SSOLoginVerify
from .global_search import GlobalSearchView
from .add_restaurant_details_view import AddRestaurantDetailsView,RestaurantMergeAPIView
from .add_tour_operator_view import AddTourOperatorViewSet,TourOperatorMergeAPIView
from .add_blood_bank_view import AddMoreBloodBankViewSet,BloodBankMergeAPIView
from .add_veterinary_hospital_view import AddMoreVeterinaryHospitalViewSet,VeterinaryHospitalMergeAPIView
from .add_pooja_stores_view import AddMorePoojaStoreViewSet,PoojaStoreMergeAPIView
from .add_hotel_view import AddMoreHotelViewSet,HotelMergeAPIView
from .add_hospital_view import AddMoreHospitalViewSet,HospitalMergeAPIView
from .add_tourism_view import AddTourismPlaceViewSet,TourismPlaceMergeAPIView
from .add_welfare_view import AddWelfareHomeViewSet,WelfareHomeMergeAPIView