# Generated by Django 5.1.7 on 2026-02-17 06:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hindu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='active_count',
            field=models.IntegerField(db_column='active_count', default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='inactive_count',
            field=models.IntegerField(db_column='inactive_count', default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], db_column='gender', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('MARRIED', 'MARRIED'), ('UNMARRIED', 'UNMARRIED'), ('OTHER', 'OTHER')], db_column='marital_status', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AddTourismPlace',
            fields=[
                ('_id', models.CharField(db_column='_id', db_index=True, default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, db_column='desc', null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('map_location', models.CharField(blank=True, max_length=500, null=True)),
                ('image_location', models.JSONField(blank=True, default=list, null=True)),
                ('timings', models.CharField(blank=True, db_column='timings', max_length=255, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], db_column='status', db_index=True, default='INACTIVE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tourism_id', models.ForeignKey(blank=True, db_column='tourism_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='hindu.templenearbytourismplace')),
                ('user_id', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'add_tourismplace',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AddWelfareHome',
            fields=[
                ('_id', models.CharField(db_column='_id', db_index=True, default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, db_column='name', db_index=True, max_length=45, null=True)),
                ('desc', models.TextField(blank=True, db_column='desc', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('image_location', models.JSONField(blank=True, db_column='image_location', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], db_column='status', db_index=True, default='INACTIVE', max_length=50)),
                ('address', models.CharField(blank=True, db_column='address', max_length=500, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_government', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], db_column='is_government', default='No', max_length=20)),
                ('established_year', models.CharField(blank=True, db_column='established_year', max_length=50, null=True)),
                ('medical_care', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='No', max_length=20)),
                ('food_and_shelter', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='No', max_length=20)),
                ('counseling_services', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='No', max_length=20)),
                ('rehabilitation_programs', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='No', max_length=20)),
                ('skill_training', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='No', max_length=20)),
                ('mental_health_support', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='No', max_length=20)),
                ('legal_aid', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='No', max_length=20)),
                ('is_24_7_support', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='No', max_length=20)),
                ('security', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='No', max_length=20)),
                ('education', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='No', max_length=20)),
                ('physiotherapy', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='No', max_length=20)),
                ('play_area', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='No', max_length=20)),
                ('recreational_activities', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='No', max_length=20)),
                ('adoption_services', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='No', max_length=20)),
                ('family_counseling', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='No', max_length=20)),
                ('emergency_response', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='No', max_length=20)),
                ('special_needs_support', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='No', max_length=20)),
                ('map_location', models.URLField(blank=True, db_column='map_location', null=True)),
                ('welfare_fee', models.CharField(blank=True, db_column='welfare_fee', max_length=500, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('welfare_id', models.ForeignKey(blank=True, db_column='welfare_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hindu.welfarehomes')),
            ],
            options={
                'db_table': 'add_welfare_homes',
            },
        ),
    ]
